# Generated by Django 4.2.2 on 2026-02-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LensOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable internal code, e.g. CLEAR, BLUE_LIGHT, SUN_TINTED, INDEX_167, AR_PREMIUM', max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('option_type', models.CharField(choices=[('COLOR_TYPE', 'Color Type'), ('COLOR', 'Color'), ('INDEX', 'Index'), ('COATING', 'Coating')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add_on_price', models.DecimalField(decimal_places=2, default=0, help_text='Additional price for selecting this option.', max_digits=8)),
                ('image_url', models.CharField(blank=True, default='', help_text='Optional image / preview / swatch URL.', max_length=4096)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional structured metadata for frontend rendering.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lens Option',
                'verbose_name_plural': 'Lens Options',
                'db_table': 'LensOption',
                'ordering': ['option_type', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LensStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('COLOR_TYPE', 'Color Type'), ('COLOR', 'Color'), ('INDEX', 'Index'), ('COATING', 'Coating')], max_length=50, unique=True)),
                ('label', models.CharField(help_text='Display label shown to users (can be changed in admin).', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lens Step',
                'verbose_name_plural': 'Lens Steps',
                'db_table': 'LensStep',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LensStepRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('current_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rules', to='lens_workflow.lensstep')),
                ('next_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rules', to='lens_workflow.lensstep')),
                ('selected_option', models.ForeignKey(help_text='The option chosen at the current step.', on_delete=django.db.models.deletion.CASCADE, related_name='step_rules', to='lens_workflow.lensoption')),
            ],
            options={
                'verbose_name': 'Lens Step Rule',
                'verbose_name_plural': 'Lens Step Rules',
                'db_table': 'LensStepRule',
                'ordering': ['current_step__sort_order', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LensOptionAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('child_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_from_parents', to='lens_workflow.lensoption')),
                ('parent_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_children', to='lens_workflow.lensoption')),
            ],
            options={
                'verbose_name': 'Lens Option Availability',
                'verbose_name_plural': 'Lens Option Availabilities',
                'db_table': 'LensOptionAvailability',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lensoption',
            index=models.Index(fields=['option_type', 'is_active', 'sort_order'], name='LensOption_option__d80933_idx'),
        ),
        migrations.AddIndex(
            model_name='lensoption',
            index=models.Index(fields=['code'], name='LensOption_code_a25dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='lenssteprule',
            index=models.Index(fields=['current_step', 'is_active'], name='LensStepRul_current_3174b3_idx'),
        ),
        migrations.AddIndex(
            model_name='lenssteprule',
            index=models.Index(fields=['selected_option', 'is_active'], name='LensStepRul_selecte_9d6b34_idx'),
        ),
        migrations.AddConstraint(
            model_name='lenssteprule',
            constraint=models.UniqueConstraint(fields=('current_step', 'selected_option'), name='uq_lens_step_rule_current_step_selected_option'),
        ),
        migrations.AddIndex(
            model_name='lensoptionavailability',
            index=models.Index(fields=['parent_option', 'is_active', 'sort_order'], name='LensOptionA_parent__e9ff66_idx'),
        ),
        migrations.AddIndex(
            model_name='lensoptionavailability',
            index=models.Index(fields=['child_option', 'is_active'], name='LensOptionA_child_o_7aad5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='lensoptionavailability',
            constraint=models.UniqueConstraint(fields=('parent_option', 'child_option'), name='uq_lens_option_availability_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='lensoptionavailability',
            constraint=models.CheckConstraint(check=models.Q(('parent_option', models.F('child_option')), _negated=True), name='ck_lens_option_availability_no_self_reference'),
        ),
    ]
