# Generated by Django 4.2.2 on 2026-09-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens_workflow', '0010_index_variants_and_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenscoloroption',
            name='base_color',
            field=models.CharField(blank=True, help_text="Color family name without density/type prefix, e.g. 'Gray' for both '50% Gray' and '80% Gray' — lets the frontend group same-hue options together if needed. Optional.", max_length=40),
        ),
        migrations.AddField(
            model_name='lenscoloroption',
            name='swatch_density',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Swatch opacity, 0.00-1.00 — e.g. 0.50 for a '50%' tint vs 0.80 for '80%' of the same base color, so two densities of the same hue render as visibly different dots.", max_digits=3),
        ),
        migrations.AddField(
            model_name='lenscoloroption',
            name='swatch_family',
            field=models.CharField(choices=[('solid', 'Solid'), ('polarized', 'Polarized'), ('mirrored', 'Mirrored'), ('photochromic', 'Photochromic')], default='solid', help_text='Swatch visual treatment: flat tint, polarized banding, mirrored shine gradient, or photochromic clear-to-tint gradient.', max_length=20),
        ),
        migrations.AddField(
            model_name='lenscoloroption',
            name='swatch_hex',
            field=models.CharField(blank=True, help_text="Hex color for the option-list swatch dot, e.g. '#6B4226'. Blank falls back to a plain gray placeholder dot.", max_length=7),
        ),
    ]
