# Generated by Django 4.1.7 on 2023-06-18 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Prescription", "0001_initial"),
        ("Product", "0001_initial"),
        ("General", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=100, null=True)),
                ("account_is_active", models.BooleanField(default=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("birth_date", models.DateField(blank=True)),
                ("icon_url", models.CharField(blank=True, max_length=100)),
                ("store_credit", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=0)),
                ("in_blacklist", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "CustomerInfo",
            },
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("SHOPPINGCART", "Shopping Cart"),
                            ("WISHLIST", "Wish List"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Customer.customerinfo",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.productinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopping List",
                "verbose_name_plural": "Shopping Lists",
                "db_table": "ShoppingList",
            },
        ),
        migrations.CreateModel(
            name="CustomerSavedPrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Customer.customerinfo",
                    ),
                ),
                (
                    "PrescriptionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Prescription.prescriptioninfo",
                    ),
                ),
            ],
            options={"db_table": "customer_saved_prescription",},
        ),
        migrations.CreateModel(
            name="CustomerSavedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AddressID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="General.address",
                    ),
                ),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Customer.customerinfo",
                    ),
                ),
            ],
            options={"db_table": "customer_saved_address",},
        ),
        migrations.AddField(
            model_name="customerinfo",
            name="wish_list",
            field=models.ManyToManyField(
                through="Customer.ShoppingList", to="Product.productinfo"
            ),
        ),
    ]
