# Generated by Django 4.1.7 on 2023-07-05 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Customer", "0001_initial"),
        ("Product", "0001_initial"),
        ("General", "0001_initial"),
        ("Prescription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinfo",
            name="wish_list",
            field=models.ManyToManyField(
                through="Customer.ShoppingList", to="Product.productinfo"
            ),
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Product.productinfo"
            ),
        ),
        migrations.AddField(
            model_name="customersavedprescription",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customersavedprescription",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Prescription.prescriptioninfo",
            ),
        ),
        migrations.AddField(
            model_name="customersavedaddress",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="General.address"
            ),
        ),
        migrations.AddField(
            model_name="customersavedaddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
