# Generated by Django 4.2.2 on 2023-07-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
