# Generated by Django 4.2.2 on 2023-07-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customerinfo_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='icon_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
