# Generated by Django 4.2.2 on 2023-07-13 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_customerinfo_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersavedaddress',
            options={'verbose_name': 'CustomerSavedAddress', 'verbose_name_plural': 'CustomerSavedAddresses'},
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='customer_saved_payment',
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='city',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='country',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='full_name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='null', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='post_code',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='province_state',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersavedaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customersavedpayment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_method', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customersavedaddress',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customersavedaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='customersavedaddress',
            table='CustomerSavedAddress',
        ),
    ]
