# Generated by Django 4.2.2 on 2023-07-14 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0001_initial'),
        ('Order', '0005_remove_completeset_options'),
        ('Customer', '0005_alter_customersavedaddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='customer_saved_addresses',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='wish_list',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='quantity',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='saved_prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prescription.prescriptioninfo'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='product',
        ),
        migrations.DeleteModel(
            name='CustomerSavedPrescription',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='product',
            field=models.ManyToManyField(to='Order.completeset'),
        ),
    ]
