# Generated by Django 4.2.2 on 2023-07-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0001_initial'),
        ('Customer', '0006_remove_customerinfo_customer_saved_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='saved_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prescription.prescriptioninfo'),
        ),
    ]
