# Generated by Django 4.2.2 on 2023-11-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_customerinfo_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='store_credit',
        ),
        migrations.CreateModel(
            name='StoreCreditActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0)),
                ('change_amount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_credit_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Credit Activity',
                'verbose_name_plural': 'Store Credit Activities',
                'db_table': 'StoreCreditActivity',
            },
        ),
    ]
