# Generated by Django 4.2.2 on 2023-11-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_remove_customerinfo_store_credit_storecreditactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='saved_prescription',
        ),
    ]
