# Generated by Django 4.2.2 on 2023-11-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_remove_customerinfo_saved_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
