# Generated by Django 4.2.2 on 2023-11-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_alter_customerinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersavedaddress',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
