# Generated by Django 4.2.2 on 2023-12-04 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_alter_orderinfo_customer'),
        ('Customer', '0018_remove_wishlist_customer_customerinfo_wish_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyeglasses_set', models.ManyToManyField(blank=True, to='Order.completeset')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
                'db_table': 'ShoppingCart',
            },
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='Customer.shoppingcart'),
        ),
    ]
