# Generated by Django 4.2.2 on 2024-01-09 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_shoppingcart_delete_shoppinglist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('brief', models.CharField(blank=True, max_length=150, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Notification',
                'verbose_name_plural': 'Customer Notifications',
                'db_table': 'CustomerNotification',
            },
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True)),
                ('message_from', models.CharField(blank=True, choices=[('Customer Service', 'Customer Service'), ('Customer', 'Customer')], max_length=100, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Message',
                'verbose_name_plural': 'Customer Messages',
                'db_table': 'CustomerMessage',
            },
        ),
    ]
