# Generated by Django 4.1.7 on 2023-06-20 01:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Supplier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_number", models.CharField(max_length=20)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "rmb_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField(null=True)),
                (
                    "letter_size",
                    models.CharField(
                        choices=[
                            ("XS", "xs"),
                            ("S", "s"),
                            ("M", "m"),
                            ("L", "l"),
                            ("XL", "xl"),
                        ],
                        max_length=10,
                    ),
                ),
                ("string_size", models.CharField(max_length=10)),
                (
                    "frame_weight",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ]
                    ),
                ),
                ("bifocal", models.BooleanField(default=False)),
                ("frame_width", models.IntegerField()),
                ("lens_width", models.IntegerField()),
                ("bridge", models.IntegerField()),
                ("temple_length", models.IntegerField()),
                ("lens_height", models.IntegerField()),
                ("upper_wearable_width", models.IntegerField()),
                ("lower_wearable_width", models.IntegerField()),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("ACETATE", "Acetate"),
                            ("TITANIUM", "Titanium"),
                            ("PLASTIC", "Plastic"),
                            ("CARBONFIBER", "Carbon Fiber"),
                            ("MIXED", "Mixed"),
                            ("METAL", "Metal"),
                            ("ALUMINIUMALLOY", "Aluminium Alloy"),
                            ("WOOD", "Wood"),
                            ("TR90", "tr90"),
                            ("ULTEM", "Ultem"),
                            ("MEMORYTITANIUM", "Memory Titanium"),
                            ("STAINLESSSTEEL", "Stainless Steel"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("RECTANGLE", "Rectangle"),
                            ("ROUND", "Round"),
                            ("SQUARE", "Square"),
                            ("OVAL", "Oval"),
                            ("CATEYE", "Cat-Eye"),
                            ("AVIATOR", "Aviator"),
                            ("HORN", "Horn"),
                            ("BROWLINE", "Browline"),
                            ("GEOMETRIC", "Geometric"),
                            ("HEART", "Heart"),
                            ("BUTTERFLY", "Butterfly"),
                            ("IRREGULAR", "Irregular"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("UNISEX", "Unisex"),
                        ],
                        default="UNISEX",
                        max_length=20,
                    ),
                ),
                (
                    "nose_pad",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("ASIANFIT", "Asian Fit"),
                            ("ADJUSTABLE", "Adjustable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frame_style",
                    models.CharField(
                        choices=[
                            ("FULLRIM", "Full-Rim"),
                            ("SEMIRIMLESS", "Semi-Rimless"),
                            ("RIMLESS", "Rimless"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pd_upper_range", models.IntegerField(default=80)),
                ("pd_lower_range", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Supplier.supplierinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "ProductInfo",
            },
        ),
        migrations.CreateModel(
            name="ProductInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, null=True, unique=True)),
                ("sku", models.CharField(max_length=20, unique=True)),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "reduced_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("carousel_img", models.CharField(max_length=1000)),
                ("detail_img", models.CharField(max_length=1000)),
                ("color_img_url", models.URLField()),
                (
                    "color_base_name",
                    models.CharField(
                        choices=[
                            ("aqua", "Aqua"),
                            ("black", "Black"),
                            ("blue", "Blue"),
                            ("fuchsia", "Fuchsia"),
                            ("gray", "Gray"),
                            ("green", "Green"),
                            ("lime", "Lime"),
                            ("maroon", "Maroon"),
                            ("navy", "Navy"),
                            ("olive", "Olive"),
                            ("orange", "Orange"),
                            ("purple", "Purple"),
                            ("red", "Red"),
                            ("silver", "Silver"),
                            ("teal", "Teal"),
                            ("white", "White"),
                            ("yellow", "Yellow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color_display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("online", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productInstance",
                        to="Product.productinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Instance",
                "verbose_name_plural": "Product Instances",
                "db_table": "ProductInstance",
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, null=True, unique=True)),
                ("category", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ManyToManyField(blank=True, to="Product.productinfo"),
                ),
            ],
            options={
                "verbose_name": "Product Tag",
                "verbose_name_plural": "Product Tags",
                "db_table": "ProductTag",
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, null=True, unique=True)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True)),
                ("user_email", models.EmailField(max_length=254)),
                ("online", models.BooleanField(default=False)),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvedby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productinfo",
                        to="Product.productinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
                "db_table": "ProductReview",
            },
        ),
        migrations.CreateModel(
            name="ProductPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                (
                    "promo_type",
                    models.CharField(
                        choices=[
                            ("1+1", "1+1"),
                            ("priceoff", "Price-Off"),
                            ("percentoff", "Percentage-Off"),
                        ],
                        default="priceoff",
                        max_length=50,
                    ),
                ),
                (
                    "promo_value",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "slug",
                    models.SlugField(
                        default="", help_text="Do not edit this field!", unique=True
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("promo_img", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "productInstance",
                    models.ManyToManyField(blank=True, to="Product.productinstance"),
                ),
            ],
            options={
                "verbose_name": "Product Promotion",
                "verbose_name_plural": "Product Promotions",
                "db_table": "ProductPromotion",
            },
        ),
    ]
