# Generated by Django 4.1.7 on 2023-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_remove_productinfo_material_remove_productinfo_shape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinstance",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
