# Generated by Django 4.1.7 on 2023-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_productdimension_slug_productfeature_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfeature",
            name="product",
            field=models.ManyToManyField(blank=True, to="Product.productinfo"),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="product",
            field=models.ManyToManyField(blank=True, to="Product.productinfo"),
        ),
    ]
