# Generated by Django 4.2.2 on 2023-10-30 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_productinstance_carousel_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color_img', models.ImageField(upload_to='product_color_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Color Image',
                'verbose_name_plural': 'Product Color Images',
                'db_table': 'ProductColorImg',
            },
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='color_img_url',
        ),
        migrations.AddField(
            model_name='productinstance',
            name='color_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.productcolorimg'),
        ),
    ]
