# Generated by Django 4.2.2 on 2023-11-04 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0003_productcolorimg_remove_productinstance_color_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productReview', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='productTag', to='Product.productinfo'),
        ),
    ]
