# Generated by Django 4.1.7 on 2023-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_alter_productfeature_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinfo",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
