# Generated by Django 4.1.7 on 2023-06-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_alter_productinstance_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinstance",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
