# Generated by Django 4.1.7 on 2023-05-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_alter_productinfo_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="slug",
            field=models.SlugField(
                default="", help_text="Do not edit this field!", unique=True
            ),
        ),
    ]
