# Generated by Django 4.1.7 on 2023-06-25 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
        ("Product", "0004_alter_productinstance_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productReivew",
                to="Customer.customerinfo",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productReview",
                to="Product.productinfo",
            ),
        ),
    ]
