# Generated by Django 4.2.2 on 2023-11-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_productreview_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='frame_style',
            field=models.CharField(choices=[('Full-Rim', 'Full-Rim'), ('Semi-Rimless', 'Semi-Rimless'), ('Rimless', 'Rimless')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='letter_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='nose_pad',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Asian Fit', 'Asian Fit'), ('Adjustable', 'Adjustable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='promo_type',
            field=models.CharField(choices=[('1+1', '1+1'), ('Price-Off', 'Price-Off'), ('Percentage-Off', 'Percentage-Off')], default='Price-Off', max_length=50),
        ),
    ]
