# Generated by Django 4.1.7 on 2023-05-04 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Supplier", "0001_initial"),
        ("Product", "0005_productinfo_name_productinfo_original_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="supplierID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Supplier.supplierinfo",
            ),
        ),
    ]
