# Generated by Django 4.1.7 on 2023-06-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0005_productreview_customer_alter_productreview_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="productreview", name="user_email",),
    ]
