# Generated by Django 4.2.2 on 2023-11-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_productinfo_frame_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='category',
            field=models.CharField(choices=[('Material', 'Material'), ('Shape', 'Shape'), ('Undefined', 'Undefined'), ('Top Selection for All', 'Top Selection for All'), ('Top Selection for Men', 'Top Selection for Men'), ('Top Selection for Women', 'Top Selection for Women'), ('Top Selection for Fashionista', 'Top Selection for Fashionista'), ('Promotion', 'Promotion'), ('Other', 'Other')], default='Undefined', max_length=50),
        ),
    ]
