# Generated by Django 4.1.7 on 2023-05-05 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Color", "0001_initial"),
        ("Product", "0006_productinfo_supplierid"),
    ]

    operations = [
        migrations.RemoveField(model_name="productinfo", name="color_name",),
        migrations.AddField(
            model_name="productinfo",
            name="colorID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Color.colorinfo",
            ),
        ),
    ]
