# Generated by Django 4.2.2 on 2024-01-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_producttag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpromotion',
            name='productInstance',
            field=models.ManyToManyField(blank=True, related_name='productPromotion', to='Product.productinstance'),
        ),
    ]
