# Generated by Django 4.1.7 on 2023-05-05 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0007_remove_productinfo_color_name_productinfo_colorid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfeature",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "slug",
                    models.SlugField(
                        default="", help_text="Do not edit this field!", unique=True
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "display_order",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ManyToManyField(blank=True, to="Product.productinfo"),
                ),
            ],
            options={
                "verbose_name": "Product Collection",
                "verbose_name_plural": "Product Collections",
                "db_table": "ProductCollection",
            },
        ),
    ]
