# Generated by Django 4.1.7 on 2023-05-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Color", "0001_initial"),
        ("Product", "0008_alter_productfeature_name_alter_productimage_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productreview", old_name="ProductID", new_name="productID",
        ),
        migrations.RemoveField(model_name="productdimension", name="productID",),
        migrations.RemoveField(model_name="productimage", name="productID",),
        migrations.AddField(
            model_name="productinfo",
            name="dimensionID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productdimension",
                to="Product.productdimension",
            ),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="imageID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productimage",
                to="Product.productimage",
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="colorID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productcolor",
                to="Color.colorinfo",
            ),
        ),
    ]
