# Generated by Django 4.2.2 on 2026-09-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_productinstance_price_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('carousel', 'Carousel'), ('detail', 'Detail'), ('mask', 'Mask')], default='carousel', max_length=20),
        ),
        # NOTE: makemigrations also picked up an unrelated, pre-existing
        # drift on ProductInfo.model_number (db_index=True not yet
        # migrated) — deliberately left out of this migration; it's
        # tracked separately and not part of this change.
    ]
