# Generated by Django 4.1.7 on 2023-05-08 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Product", "0009_rename_productid_productreview_productid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage", old_name="path", new_name="image_url",
        ),
        migrations.RenameField(
            model_name="productinfo", old_name="original_price", new_name="base_price",
        ),
        migrations.RemoveField(model_name="productinfo", name="colorID",),
        migrations.RemoveField(model_name="productinfo", name="imageID",),
        migrations.RemoveField(model_name="productreview", name="approved_by",),
        migrations.AlterField(
            model_name="productreview",
            name="productID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productinfo",
                to="Product.productinfo",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvedby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
