# Generated by Django 4.2.2 on 2026-09-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_productinfo_model_number'),
        ('Product', '0010_productimage_mask_type'),
    ]

    operations = [
    ]
