# Generated by Django 4.1.7 on 2023-05-18 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Color", "0001_initial"),
        ("Product", "0010_rename_path_productimage_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="colorID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productimage",
                to="Color.colorinfo",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="productID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productimage",
                to="Product.productinfo",
            ),
        ),
    ]
