# Generated by Django 4.1.7 on 2023-03-25 21:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewInfo",
            fields=[
                ("ReviewID", models.AutoField(primary_key=True, serialize=False)),
                ("ReviewTitle", models.CharField(max_length=100)),
                ("ReviewContent", models.TextField()),
                ("ReviewUserEmail", models.EmailField(max_length=254)),
                ("ReviewOnline", models.BooleanField(default=False)),
                ("ReviewSKU", models.CharField(max_length=100)),
                (
                    "ReviewRating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "ReviewApprovedBy",
                    models.ManyToManyField(to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
