# Generated by Django 4.1.7 on 2023-03-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReviewInfo",
            fields=[
                ("ReviewID", models.AutoField(primary_key=True, serialize=False)),
                ("ReviewTitle", models.CharField(max_length=100)),
                ("ReviewContent", models.TextField()),
            ],
        ),
    ]
