# Generated by Django 4.1.7 on 2023-03-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSite", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewinfo",
            old_name="ReviewApprovedBy",
            new_name="approved_by",
        ),
        migrations.RenameField(
            model_name="reviewinfo", old_name="ReviewContent", new_name="content",
        ),
        migrations.RenameField(
            model_name="reviewinfo", old_name="ReviewOnline", new_name="online",
        ),
        migrations.RenameField(
            model_name="reviewinfo", old_name="ReviewRating", new_name="rating",
        ),
        migrations.RenameField(
            model_name="reviewinfo", old_name="ReviewSKU", new_name="sku",
        ),
        migrations.RenameField(
            model_name="reviewinfo", old_name="ReviewTitle", new_name="title",
        ),
        migrations.RenameField(
            model_name="reviewinfo", old_name="ReviewUserEmail", new_name="user_email",
        ),
    ]
