# Generated by Django 4.1.7 on 2023-04-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSite", "0003_address_customerinfo_customersavedaddress_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerinfo",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="orderimage",
            options={
                "verbose_name": "Order Image",
                "verbose_name_plural": "Order Images",
            },
        ),
        migrations.AlterModelOptions(
            name="orderinfo",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="ordertax",
            options={"verbose_name": "Order Tax", "verbose_name_plural": "Order Tax"},
        ),
        migrations.AlterModelOptions(
            name="productdimension",
            options={
                "verbose_name": "Product Dimension",
                "verbose_name_plural": "Product Dimensions",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.AlterModelOptions(
            name="productinfo",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppinglist",
            options={
                "verbose_name": "Shopping List",
                "verbose_name_plural": "Shopping Lists",
            },
        ),
        migrations.AlterModelTable(name="customerinfo", table="CustomerInfo",),
        migrations.AlterModelTable(
            name="customersavedaddress", table="customer_saved_address",
        ),
        migrations.AlterModelTable(name="orderhasaddress", table="order_has_address",),
        migrations.AlterModelTable(name="orderimage", table="OrderImage",),
        migrations.AlterModelTable(name="orderinfo", table="OrderInfo",),
        migrations.AlterModelTable(name="orderlineitem", table="order_line_item",),
        migrations.AlterModelTable(name="ordertax", table="OrderTax",),
        migrations.AlterModelTable(name="productdimension", table="ProductDimension",),
        migrations.AlterModelTable(name="productimage", table="ProductImage",),
        migrations.AlterModelTable(name="productinfo", table="ProductInfo",),
        migrations.AlterModelTable(name="productreview", table="ProductReview",),
        migrations.AlterModelTable(name="shoppinglist", table="ShoppingList",),
    ]
