# Generated by Django 4.1.7 on 2023-04-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "AdminSite",
            "0004_alter_customerinfo_options_alter_orderimage_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelTable(name="address", table="Address",),
    ]
