# Generated by Django 4.1.7 on 2023-07-05 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Accessory", "0001_initial"),
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineaccessory",
            name="orderID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Order.orderinfo"
            ),
        ),
        migrations.AddField(
            model_name="accessoryinfo",
            name="order",
            field=models.ManyToManyField(
                blank=True, through="Accessory.OrderLineAccessory", to="Order.orderinfo"
            ),
        ),
        migrations.AddField(
            model_name="accessoryimage",
            name="accessory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Accessory.accessoryinfo",
            ),
        ),
    ]
