# Generated by Django 4.2.2 on 2023-10-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='home_page_img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
