# Generated by Django 4.2.2 on 2024-04-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='category',
            field=models.CharField(default='Other', max_length=150),
        ),
    ]
