# Generated by Django 4.2.2 on 2026-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_bloginfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='category',
            field=models.CharField(db_index=True, default='Other', max_length=150),
        ),
    ]
