# Generated by Django 4.2.2 on 2026-10-01 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_bloginfo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, default='Other', max_length=150)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True)),
                ('brief', models.TextField(blank=True, null=True)),
                ('home_page_img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'BlogPreview',
            },
        ),
    ]
