# Generated by Django 4.1.7 on 2023-06-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrescriptionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pd_l", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pd_r", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "sphere_l",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "sphere_r",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "cylinder_l",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "cylinder_r",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("axis_l", models.IntegerField(blank=True)),
                ("axis_r", models.IntegerField(blank=True)),
                (
                    "base_l",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "base_r",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "nv_add",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Presctiption",
                "verbose_name_plural": "Presctiptions",
            },
        ),
        migrations.CreateModel(
            name="PrescriptionPrism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horizontal_value_l",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "horizontal_direction_l",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "horizontal_value_r",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "horizontal_direction_r",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "vertical_value_l",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "vertical_direction_l",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "vertical_value_r",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "vertical_direction_r",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "prescriptionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Prescription.prescriptioninfo",
                    ),
                ),
            ],
            options={"verbose_name": "Prism", "verbose_name_plural": "Prism",},
        ),
    ]
