# Generated by Django 4.1.7 on 2023-04-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Prescription", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescriptionprism",
            old_name="PrescriptionID",
            new_name="prescriptionID",
        ),
    ]
