# Generated by Django 4.1.7 on 2023-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Prescription", "0002_rename_prescriptionid_prescriptionprism_prescriptionid"),
    ]

    operations = [
        migrations.RemoveField(model_name="prescriptioninfo", name="prism_l",),
        migrations.RemoveField(model_name="prescriptioninfo", name="prism_r",),
        migrations.AlterField(
            model_name="prescriptioninfo",
            name="base_l",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="prescriptioninfo",
            name="base_r",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="prescriptioninfo",
            name="cylinder_l",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="prescriptioninfo",
            name="cylinder_r",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="prescriptioninfo",
            name="nv_add",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="prescriptioninfo",
            name="sphere_l",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="prescriptioninfo",
            name="sphere_r",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
