# Generated by Django 4.2.2 on 2023-11-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0003_prescriptioninfo_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptioninfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='axis_l',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='axis_r',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='base_l',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='base_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='cylinder_l',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='cylinder_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='nv_add',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='pd_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='pd_r',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='sphere_l',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='sphere_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
