# Generated by Django 4.1.7 on 2023-04-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Prescription", "0003_remove_prescriptioninfo_prism_l_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prescriptioninfo",
            options={
                "verbose_name": "Presctiption",
                "verbose_name_plural": "Presctiptions",
            },
        ),
        migrations.AlterModelOptions(
            name="prescriptionprism",
            options={"verbose_name": "Prism", "verbose_name_plural": "Prism"},
        ),
    ]
