# Generated by Django 4.2.2 on 2023-11-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0004_prescriptioninfo_nickname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptioninfo',
            options={'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
    ]
