# Generated by Django 4.2.2 on 2023-11-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0005_alter_prescriptioninfo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptioninfo',
            old_name='nv_add',
            new_name='add_l',
        ),
        migrations.AddField(
            model_name='prescriptioninfo',
            name='add_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
