# Generated by Django 4.2.2 on 2023-11-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0006_rename_nv_add_prescriptioninfo_add_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='axis_l',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='axis_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
