# Generated by Django 4.2.2 on 2026-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0008_prescriptioninfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionprism',
            name='horizontal_direction_l',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionprism',
            name='horizontal_direction_r',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionprism',
            name='horizontal_value_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionprism',
            name='horizontal_value_r',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionprism',
            name='vertical_direction_l',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionprism',
            name='vertical_direction_r',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionprism',
            name='vertical_value_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionprism',
            name='vertical_value_r',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
