# Generated by Django 4.2.2 on 2023-08-14 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0001_initial'),
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('frame_discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='Percentage', max_length=50)),
                ('frame_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lens_discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='Percentage', max_length=50)),
                ('lens_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='Percentage', max_length=50)),
                ('shipping_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order_discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='Percentage', max_length=50)),
                ('order_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_product', models.ManyToManyField(related_name='coupons', to='Product.productinstance')),
                ('valid_customer', models.ManyToManyField(related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'Coupon',
            },
        ),
    ]
