# Generated by Django 4.2.2 on 2023-10-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Upload',
                'verbose_name_plural': 'Image Uploads',
                'db_table': 'ImageUpload',
            },
        ),
    ]
