# Generated by Django 4.2.2 on 2023-11-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_address_customer_address_default_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
