# Generated by Django 4.2.2 on 2023-12-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_alter_address_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency Conversion',
                'verbose_name_plural': 'Currency Conversions',
                'db_table': 'CurrencyConversion',
            },
        ),
    ]
