# Generated by Django 4.2.2 on 2024-05-21 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0008_alter_productpromotion_productinstance'),
        ('General', '0008_pageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applied_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupons', to='Product.productinstance'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_customer',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
