# Generated by Django 4.2.2 on 2026-02-23 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_productpromotion_productinstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('General', '0009_alter_coupon_applied_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applied_product',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='Product.productinstance'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_customer',
            field=models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
