# Generated by Django 4.2.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0011_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Question and Answer', 'verbose_name_plural': 'Questions and Answers'},
        ),
    ]
