# Generated by Django 4.1.7 on 2023-06-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LensProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "add_on_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completeSetID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.completeset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lens Property",
                "verbose_name_plural": "Lens Properties",
            },
        ),
        migrations.CreateModel(
            name="LensOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "add_on_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completeSetID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.completeset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lens Option",
                "verbose_name_plural": "Lens Options",
            },
        ),
    ]
