# Generated by Django 4.2.2 on 2023-07-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('Lens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LensOpeions',
            new_name='LensOptions',
        ),
    ]
