# Generated by Django 4.1.7 on 2023-04-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Lens", "0001_initial"),
        ("Order", "0002_completeset_ordercompleteprescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="lensproperty",
            name="CompleteSetID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Order.completeset"
            ),
        ),
        migrations.AddField(
            model_name="lensoptions",
            name="CompleteSetID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Order.completeset"
            ),
        ),
    ]
