# Generated by Django 4.1.7 on 2023-04-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Lens", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lensoptions",
            old_name="CompleteSetID",
            new_name="completeSetID",
        ),
        migrations.RenameField(
            model_name="lensproperty",
            old_name="CompleteSetID",
            new_name="completeSetID",
        ),
    ]
