# Generated by Django 4.2.2 on 2023-07-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0002_rename_lensopeions_lensoptions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lensoptions',
            table='LensOptions',
        ),
    ]
