# Generated by Django 4.1.7 on 2023-04-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Lens", "0003_rename_completesetid_lensoptions_completesetid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lensoptions",
            options={
                "verbose_name": "Lens Option",
                "verbose_name_plural": "Lens Options",
            },
        ),
        migrations.AlterModelOptions(
            name="lensproperty",
            options={
                "verbose_name": "Lens Property",
                "verbose_name_plural": "Lens Properties",
            },
        ),
    ]
