# Generated by Django 4.2.2 on 2023-07-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0003_alter_lensoptions_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensoptions',
            name='category',
            field=models.CharField(choices=[('usage', 'Usage'), ('color', 'Color'), ('coating', 'Coating'), ('density', 'Density'), ('index', 'Index')], default='usage', max_length=50),
        ),
        migrations.AlterField(
            model_name='lensoptions',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
