# Generated by Django 4.2.2 on 2023-07-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0004_lensoptions_category_alter_lensoptions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lensoptions',
            name='category',
            field=models.CharField(choices=[('usage', 'Usage'), ('color', 'Color'), ('coating', 'Coating'), ('density', 'Density'), ('index', 'Index'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
