# Generated by Django 4.2.2 on 2023-07-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0006_lensoptions_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add_on_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image_url', models.CharField(default='', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Coating',
                'verbose_name_plural': 'Lens Coating',
                'db_table': 'LensCoating',
            },
        ),
        migrations.CreateModel(
            name='LensColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Clear', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add_on_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image_url', models.CharField(default='', max_length=4096)),
                ('available_colors', models.CharField(default='', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Color',
                'verbose_name_plural': 'Lens Color',
                'db_table': 'LensColor',
            },
        ),
        migrations.CreateModel(
            name='LensDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add_on_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Density',
                'verbose_name_plural': 'Lens Density',
                'db_table': 'LensDensity',
            },
        ),
        migrations.CreateModel(
            name='LensIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard(1.56)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add_on_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image_url', models.CharField(default='', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Index',
                'verbose_name_plural': 'Lens Index',
                'db_table': 'LensIndex',
            },
        ),
        migrations.CreateModel(
            name='LensUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Clear', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('add_on_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image_url', models.CharField(default='', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Usage',
                'verbose_name_plural': 'Lens Usage',
                'db_table': 'LensUsage',
            },
        ),
        migrations.RemoveField(
            model_name='lensoptions',
            name='category',
        ),
    ]
