# Generated by Django 4.2.2 on 2023-07-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0007_lenscoating_lenscolor_lensdensity_lensindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensdensity',
            name='image_url',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
