# Generated by Django 4.2.2 on 2023-07-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0008_lensdensity_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenscoating',
            name='available_next_lvl',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='lenscolor',
            name='available_next_lvl',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='lensdensity',
            name='available_next_lvl',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='lensoptions',
            name='available_next_lvl',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='lensusage',
            name='available_next_lvl',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
