# Generated by Django 4.2.2 on 2023-07-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0009_lenscoating_available_next_lvl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenscoating',
            name='available_next_lvl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lenscoating',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='lenscolor',
            name='available_next_lvl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lenscolor',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='lensdensity',
            name='available_next_lvl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lensdensity',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='lensindex',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='lensoptions',
            name='available_next_lvl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lensoptions',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='lensusage',
            name='available_next_lvl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lensusage',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
