# Generated by Django 4.2.2 on 2023-07-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_remove_completeset_options'),
        ('Lens', '0010_alter_lenscoating_available_next_lvl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LensOptions',
        ),
    ]
