# Generated by Django 4.2.2 on 2023-07-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0011_delete_lensoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lensdensity',
            name='available_next_lvl',
        ),
    ]
