# Generated by Django 4.1.7 on 2023-07-05 02:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Product", "0001_initial"),
        ("General", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Prescription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompleteSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage", models.CharField(max_length=100)),
                ("index", models.CharField(max_length=100)),
                ("customization", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.productinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complete Set",
                "verbose_name_plural": "Complete Sets",
            },
        ),
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("order_number", models.CharField(max_length=20)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("NULL", "Null"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("COMPLETE", "Complete"),
                            ("CANCELED", "Canceled"),
                            ("REFUND", "Refund"),
                        ],
                        default="PROCESSING",
                        max_length=50,
                    ),
                ),
                ("refound_status", models.CharField(blank=True, max_length=20)),
                (
                    "refound_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("PROCESSING", "Processing"),
                            ("NULL", "Null"),
                        ],
                        default="UNPAID",
                        max_length=50,
                    ),
                ),
                ("payment_type", models.CharField(max_length=20, null=True)),
                (
                    "order_device",
                    models.CharField(
                        choices=[
                            ("WINDOWS", "Windows"),
                            ("MACOS", "Mac OS"),
                            ("ANDROID", "Android"),
                            ("IOS", "ios"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=50,
                    ),
                ),
                (
                    "store_credit_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "store_credit_gained",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("shipping_company", models.CharField(blank=True, max_length=50)),
                ("tracking_number", models.CharField(blank=True, max_length=50)),
                (
                    "shipping_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "accessory_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("sub_total", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("comment", models.TextField()),
                ("issue_order", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "OrderInfo",
            },
        ),
        migrations.CreateModel(
            name="OrderUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("details", models.TextField()),
                ("by", models.CharField(max_length=50)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.orderinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Update",
                "verbose_name_plural": "Order Updates",
                "db_table": "OrderUpdates",
            },
        ),
        migrations.CreateModel(
            name="OrderTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_number", models.CharField(max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gst", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("hst", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("qst", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("pst", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.orderinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Tax",
                "verbose_name_plural": "Order Tax",
                "db_table": "OrderTax",
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "payment_gateway",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paypal", "PayPal"),
                            ("ocean_payment", "Ocean Payment"),
                        ],
                        max_length=20,
                        verbose_name="Payment Gateway",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Transaction Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=20,
                        verbose_name="Transaction Status",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Transaction Date",
                    ),
                ),
                (
                    "payer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Payer Email"
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Gateway Transaction ID",
                    ),
                ),
                (
                    "payment_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Payment Response",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Order.orderinfo",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "Payment",
            },
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.orderinfo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.productinstance",
                    ),
                ),
            ],
            options={"db_table": "order_line_item",},
        ),
        migrations.AddField(
            model_name="orderinfo",
            name="product",
            field=models.ManyToManyField(
                blank=True, through="Order.OrderLineItem", to="Product.productinstance"
            ),
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_type", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("path", models.URLField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.orderinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Image",
                "verbose_name_plural": "Order Images",
                "db_table": "OrderImage",
            },
        ),
        migrations.CreateModel(
            name="OrderHasAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="General.address",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.orderinfo",
                    ),
                ),
            ],
            options={"db_table": "order_has_address",},
        ),
        migrations.CreateModel(
            name="OrderCompletePrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completeSet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.completeset",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Prescription.prescriptioninfo",
                    ),
                ),
            ],
            options={"db_table": "order_complete_prescription",},
        ),
        migrations.AddField(
            model_name="completeset",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Order.orderinfo"
            ),
        ),
    ]
