# Generated by Django 4.1.7 on 2023-04-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
        ("Prescription", "0001_initial"),
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompleteSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("index", models.CharField(max_length=100)),
                ("customization", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.orderinfo",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.productinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderCompletePrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CompleteSetID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.completeset",
                    ),
                ),
                (
                    "PrescriptionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Prescription.prescriptioninfo",
                    ),
                ),
            ],
            options={"db_table": "order_complete_prescription",},
        ),
    ]
