# Generated by Django 4.2.2 on 2023-07-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0002_rename_lensopeions_lensoptions'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeset',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='completeset',
            name='index',
        ),
        migrations.RemoveField(
            model_name='completeset',
            name='usage',
        ),
        migrations.AddField(
            model_name='completeset',
            name='options',
            field=models.ManyToManyField(to='Lens.lensoptions'),
        ),
        migrations.AlterField(
            model_name='completeset',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.orderinfo'),
        ),
    ]
