# Generated by Django 4.2.2 on 2023-07-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_completeset_customization_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='completeset',
            table='CompleteSet',
        ),
    ]
