# Generated by Django 4.2.2 on 2023-07-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lens', '0007_lenscoating_lenscolor_lensdensity_lensindex_and_more'),
        ('Order', '0003_alter_completeset_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeset',
            name='coating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lens.lenscoating'),
        ),
        migrations.AddField(
            model_name='completeset',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lens.lenscolor'),
        ),
        migrations.AddField(
            model_name='completeset',
            name='density',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lens.lensdensity'),
        ),
        migrations.AddField(
            model_name='completeset',
            name='index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lens.lensindex'),
        ),
        migrations.AddField(
            model_name='completeset',
            name='usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lens.lensusage'),
        ),
    ]
