# Generated by Django 4.2.2 on 2023-07-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_completeset_coating_completeset_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeset',
            name='options',
        ),
    ]
