# Generated by Django 4.2.2 on 2023-07-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_remove_completeset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeset',
            name='sub_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='completeset',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
