# Generated by Django 4.2.2 on 2023-08-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_coupon'),
        ('Order', '0006_completeset_sub_color_completeset_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='address',
            field=models.ManyToManyField(null=True, through='Order.OrderHasAddress', to='General.address'),
        ),
    ]
