# Generated by Django 4.2.2 on 2023-08-27 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_coupon'),
        ('Order', '0007_orderinfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='General.address'),
        ),
    ]
