# Generated by Django 4.2.2 on 2023-12-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0007_alter_prescriptioninfo_axis_l_and_more'),
        ('Order', '0010_alter_orderinfo_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeset',
            name='prescription',
            field=models.ManyToManyField(blank=True, to='Prescription.prescriptioninfo'),
        ),
    ]
