# Generated by Django 4.2.2 on 2024-01-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_completeset_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeset',
            name='saved_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
