# Generated by Django 4.2.2 on 2024-05-23 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0009_alter_coupon_applied_product_and_more'),
        ('Order', '0012_completeset_saved_for_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='coupon_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='General.coupon'),
        ),
    ]
