# Generated by Django 4.2.2 on 2025-06-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0007_alter_prescriptioninfo_axis_l_and_more'),
        ('Order', '0013_orderinfo_coupon_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeset',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='OrderCompletePrescription',
        ),
        migrations.AddField(
            model_name='completeset',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prescription.prescriptioninfo'),
        ),
    ]
