# Generated by Django 4.2.2 on 2026-02-25 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lens_workflow', '0001_initial'),
        ('Order', '0014_remove_completeset_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeset',
            name='coating',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'COATING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete_sets_as_coating', to='lens_workflow.lensoption'),
        ),
        migrations.AlterField(
            model_name='completeset',
            name='color',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'COLOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete_sets_as_color', to='lens_workflow.lensoption'),
        ),
        migrations.AlterField(
            model_name='completeset',
            name='density',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='completeset',
            name='index',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'INDEX'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete_sets_as_index', to='lens_workflow.lensoption'),
        ),
        migrations.AlterField(
            model_name='completeset',
            name='usage',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'COLOR_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete_sets_as_usage', to='lens_workflow.lensoption'),
        ),
    ]
