# Generated by Django 4.2.2 on 2026-03-16 12:21
#
# Recovered from production: this migration was already applied to the live
# database in March 2026 but was never committed to this repo's git history
# (a gap discovered while deploying the Shopping Flow Rebuild — see
# 0018_merge_20260729_2347 and 0021_remove_ordertax's commit for context).
# Content copied verbatim from the file already on the server so git history
# matches what's actually applied.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0016_backfill_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.CharField(choices=[('NULL', 'Null'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETE', 'Complete'), ('CANCELED', 'Canceled'), ('REFUND', 'Refund')], db_index=True, default='PROCESSING', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('NULL', 'Null')], db_index=True, default='UNPAID', max_length=50),
        ),
    ]
