# Generated by Django 4.2.2 on 2026-07-29 23:47
#
# Recovered from production — see 0017_alter_orderinfo_order_number_and_more's
# comment for why this file is being added to git history now instead of
# back in July. Content copied verbatim from the file already on the server.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_alter_orderinfo_order_number_and_more'),
        ('Order', '0017_completeset_new_lens_reference_fields'),
    ]

    operations = [
    ]
